updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "main"
    commit-message:
      prefix: "chore(deps)"
    groups:
      patches-and-minor:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "main"
    commit-message:
      prefix: "chore(ci)"
    groups:
      github-actions-patches:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - "patch"
